// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'car': string;
  'hello': string;
  'main': string;
  'paper': string;
  'path': string;
  'road': string;
  'sliderContainer': string;
  'svg': string;
}
declare var cssExports: CssExports;
export = cssExports;
