// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'car': string;
  'path': string;
  'road': string;
  'svg': string;
}
declare var cssExports: CssExports;
export = cssExports;
